import { ContentTheme } from '../types';

export const corporateTheme: ContentTheme = {
  appName: "AI Skills Tracker",
  tagline: "Learn, practice, share",
  concepts: {
    useCase: "Skill",
    useCasePlural: "Skills",
    library: "Skill Library",
    upvote: "Recommend",
    dashboard: "My Progress",
    leaderboard: "Team Rankings",
    profile: "My Profile",
    login: "Sign In",
    submit: "Submit a skill",
    step1: "Learned",
    step2: "Applied",
    step3: "Shared",
    completed: "Mastered",
    newUser: "New Member",
    recruit: "Learner",
    delete: "Delete",
    edit: "Edit",
    save: "Save Changes",
    cancel: "Cancel",
    about: "About This App",
    timeline: "Timeline",
    discussion: "Discussion",
    playbook: "Playbook",
    tip: "Tip",
    gotcha: "Gotcha",
    skillRadar: "Skill Radar",
    badges: "Badges",
    difficulty: "Difficulty",
    activityFeed: "Activity Feed",
    recommended: "Recommended For You",
    related: "Related Skills",
  },
  ranks: [
    { min: 0, name: "Newcomer", desc: "Just getting started" },
    { min: 10, name: "Learner", desc: "Building foundations" },
    { min: 30, name: "Practitioner", desc: "Applying skills daily" },
    { min: 60, name: "Advocate", desc: "Sharing knowledge actively" },
    { min: 110, name: "Champion", desc: "Driving adoption across teams" },
    { min: 210, name: "Expert", desc: "Leading the way" },
  ],
  microcopy: {
    emptyDashboard: "You haven't started any skills yet. Browse the library to begin.",
    recruitSuccess: "Nice! They've been added to your sharing history.",
    completionCelebration: "Skill mastered! Great work.",
    stubAccountWelcome: "Welcome! You've already been introduced to {count} skills by colleagues.",
    notFound: "Page not found.",
    loginSubtext: "Track your AI learning journey",
    submissionPrompt: "Share an AI use case you've found valuable",
    deleteConfirmTitle: "Delete this skill?",
    deleteConfirmBody: "This skill and all associated progress, upvotes, and shares will be permanently deleted. Type DELETE to confirm.",
    deleteConfirmPlaceholder: "Type DELETE to confirm",
    deleteConfirmButton: "Delete Permanently",
    deleteSuccess: "Skill deleted successfully.",
    editTitle: "Edit Skill",
    editTitleLabel: "Skill Title",
    editDescriptionLabel: "Description",
    editResourcesLabel: "Resources",
    editSuccess: "Skill updated successfully.",
    editError: "Failed to update skill. Please try again.",
    aboutTitle: "About This App",
    aboutContent: "This app is just for fun, to encourage more valuable use of AI at work. If it works, we'll rebuild it for real and use it to help our whole company, and maybe our clients, to adopt AI. In early pilot stages, we're doing minimum investment: vibe-coded with no human code review, hosted in a public unapproved location, no security or authentication - so don't put anything sensitive here.\n\nWe're running this like an open source project. David Friedman and Ethan Murray initiated it, but it belongs to anyone who cares to make it better. Anyone can add Issues (feature requests) or directly make code change pull requests at https://github.com/ethanmurray/ai-evangelizer; anyone can merge code and it will auto-deploy to production, so try not to break it for everyone else. It began with no design and just a few rough ideas, so feel totally free to introduce your own ideas and make changes. The only guiding principle is to build something that drives more AI adoption on valuable uses that we want more of at work.",
    checkEmailTitle: "Check Your Email",
    checkEmailBody: "We've sent a verification link to {email}. Click it to complete your registration.",
    checkEmailExpiry: "The link expires in 15 minutes.",
    verifySuccess: "Your account has been verified. Welcome!",
    verifyExpired: "This verification link has expired. Please register again.",
    verifyAlreadyUsed: "This verification link has already been used. Try signing in.",
    verifyInvalid: "This verification link is invalid. Please register again.",
    teacherPrompt: "Who taught you this skill?",
    teacherPlaceholder: "their@email.com",
    teacherSkip: "Skip",
    teacherSubmit: "Give credit",
    shareConfirmed: "Thanks for confirming! The share has been validated.",
    shareDenied: "Share declined. You can change your mind using the button below.",
    shareInvalidToken: "This link is invalid or has already been used.",
    shareStatusChanged: "Status updated from a previous response.",
    timelineEmpty: "No activity yet. Start learning!",
    noComments: "No comments yet. Start the conversation!",
    noPlaybook: "No playbook steps yet. Share your approach!",
    commentPlaceholder: "Share your thoughts...",
    rankUpTitle: "Rank Up!",
    rankUpBody: "Congratulations! You've reached {rank}.",
    feedEmpty: "No activity yet. Be the first!",
    noRecommendations: "Start learning to get personalized recommendations.",
  },
  badgeNames: {
    first_learn: { name: "First Step", description: "Learned your first skill" },
    first_apply: { name: "Applied!", description: "Applied your first skill" },
    first_share: { name: "First Share", description: "Shared a skill with a colleague" },
    ten_learned: { name: "10 Learned", description: "Learned 10 skills" },
    five_applied: { name: "5 Applied", description: "Applied 5 skills" },
    taught_five: { name: "Mentor", description: "Taught 5 different people" },
    full_stack_ai: { name: "Full Stack AI", description: "Completed a use case in every category" },
    submitted_one: { name: "Contributor", description: "Submitted a skill to the library" },
    five_completed: { name: "5 Mastered", description: "Fully mastered 5 skills" },
    speed_learner: { name: "Quick Learner", description: "Learned 3 skills in one day" },
  },
  toneGuidance: "Professional, warm, encouraging. Standard corporate L&D voice.",
};
