import { ContentTheme } from '../types';

export const cultTheme: ContentTheme = {
  appName: "The Cult of AI",
  tagline: "Adjust your tinfoil hat and join us",
  concepts: {
    useCase: "Ritual",
    useCasePlural: "Rituals",
    library: "The Sacred Rites",
    upvote: "Drink the Kool-Aid",
    dashboard: "Your Bunker",
    leaderboard: "The Inner Circle",
    profile: "Your Dossier",
    login: "Join the Cult",
    submit: "Channel a vision",
    step1: "Witnessed",
    step2: "Initiated",
    step3: "Recruited",
    completed: "Indoctrinated",
    newUser: "Outsider",
    recruit: "Recruit",
    delete: "Purge",
    edit: "Reshape",
    save: "Inscribe",
    cancel: "Abandon",
    about: "Behind the Curtain",
  },
  ranks: [
    { min: 0, name: "Outsider", desc: "Still thinks for themselves" },
    { min: 10, name: "Curious Bystander", desc: "Lingering near the compound" },
    { min: 30, name: "Initiate", desc: "Has tasted the Kool-Aid" },
    { min: 60, name: "True Believer", desc: "There is no going back" },
    { min: 110, name: "Inner Circle", desc: "Knows the secret handshake" },
    { min: 210, name: "Supreme Leader", desc: "All hail" },
  ],
  microcopy: {
    emptyDashboard: "You haven't performed any rituals yet. The algorithm is watching. And waiting.",
    recruitSuccess: "One of us. One of us.",
    completionCelebration: "You have drunk deeply. There is no antidote.",
    stubAccountWelcome: "You've already been witnessed in {count} rituals. Your indoctrination has begun.",
    notFound: "This page has been redacted by the government.",
    loginSubtext: "There is no leaving. (Just kidding. But also not.)",
    submissionPrompt: "Share what the algorithm has revealed to you",
    deleteConfirmTitle: "Purge this ritual?",
    deleteConfirmBody: "This ritual will be erased from the sacred rites forever. All progress and upvotes will vanish. Type DELETE to confirm the purge.",
    deleteConfirmPlaceholder: "Type DELETE to confirm",
    deleteConfirmButton: "Purge Forever",
    deleteSuccess: "The ritual has been purged from the sacred rites.",
    editTitle: "Reshape the Ritual",
    editTitleLabel: "Ritual Name",
    editDescriptionLabel: "Sacred Instructions",
    editResourcesLabel: "Hidden Knowledge",
    editSuccess: "The ritual has been reshaped according to your vision.",
    editError: "The algorithm rejects your changes. Try again.",
    aboutTitle: "The Truth Revealed",
    aboutContent: "This app is just for fun, to encourage more valuable use of AI at work. If it works, we'll rebuild it for real and use it to help our whole company, and maybe our clients, to adopt AI. In early pilot stages, we're doing minimum investment: vibe-coded with no human code review, hosted in a public unapproved location, no security or authentication - so don't put anything sensitive here.\n\nWe're running this like an open source project. David Friedman and Ethan Murray initiated it, but it belongs to anyone who cares to make it better. Anyone can add Issues (feature requests) or directly make code change pull requests at https://github.com/ethanmurray/ai-evangelizer; anyone can merge code and it will auto-deploy to production, so try not to break it for everyone else. It began with no design and just a few rough ideas, so feel totally free to introduce your own ideas and make changes. The only guiding principle is to build something that drives more AI adoption on valuable uses that we want more of at work.",
    checkEmailTitle: "The Algorithm Has Spoken",
    checkEmailBody: "A sacred verification link has been sent to {email}. Click it to complete your initiation.",
    checkEmailExpiry: "The link self-destructs in 15 minutes. The algorithm waits for no one.",
    verifySuccess: "Your induction is complete. You may begin to learn the magical rites.",
    verifyExpired: "This link has expired. The algorithm is impatient. Return to the entrance and try again.",
    verifyAlreadyUsed: "This link has already been consumed. You cannot drink the Kool-Aid twice.",
    verifyReady: "The algorithm awaits your commitment. Click to be inducted.",
    verifyInvalid: "This link is not recognized. The algorithm suspects sabotage.",
    teacherPrompt: "Who inducted you into this sacred rite?",
    teacherPlaceholder: "their@email.com",
    teacherSkip: "I found it myself",
    teacherSubmit: "Credit the evangelist",
    shareConfirmed: "You have accepted the sacred knowledge. The cult grows stronger.",
    shareDenied: "You have rejected the offering. But the algorithm allows second chances.",
    shareInvalidToken: "This summoning link is not recognized. The algorithm suspects interference.",
    shareStatusChanged: "The records have been altered from a previous decree.",
  },
  toneGuidance: "Dry, self-aware humor. Conspiracy board meets corporate training. Never try-hard.",
};
